### PR TITLE
Refactor login

### PR DESCRIPTION
**Pull request by azzamsa**

### CODE REVIEW

**Comment by azzamsa** [comment]
Please don't merge this request. We still have some issue to fix

**Comment by azzamsa** [comment]
Closing as https://github.com/BiznetGIO/neo-cli/pull/108

**Comment by anak10thn** [comment]
why?

**Comment by azzamsa** [comment]
@anak10thn Yes. I moved all development to https://github.com/BiznetGIO/neo-cli/pull/108 this branch

**Pull request closed without merging**
